VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu-14.04"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network "private_network", ip: "192.168.33.71"
  config.vm.network "forwarded_port", guest: 8080, host: 5000

  config.vm.define "registrolivre" do |rl|
  end

  config.vm.provider "virtualbox" do |box|
	box.name = "registrolivre"
    box.memory = 524
  end

  config.vm.synced_folder "public_keys/", "/home/vagrant/public_keys", create: true

  # Provision
  config.vm.provision :shell, :path => "../scripts/provision/open-jdk8.sh"
  config.vm.provision :shell, :path => "scripts/provision/create-user.sh"
  config.vm.provision :shell, :path => "scripts/provision/ssh-user-permission.sh"

end