VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu-14.04"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 8153, host: 8153

  config.vm.provider "virtualbox" do |box|
	 box.name = "go-ci"
     box.memory = 1024
  end

  config.vm.provision "file", source: "../../configurations/cruise-config.xml", destination: "/tmp/cruise-config.xml"
  config.vm.provision "file", source: "../../configurations/htpasswd", destination: "/tmp/htpasswd"

  config.vm.provision "shell", path: "../../../scripts/provision/open-jdk8.sh"
  config.vm.provision "shell", path: "../provision/export_java_home.sh"
  config.vm.provision "shell", path: "../provision/git.sh"
  config.vm.provision "shell", path: "../provision/nodejs.sh"
  config.vm.provision "shell", path: "../provision/go-server.sh"
  config.vm.provision "shell", path: "../provision/go-agent.sh"
  config.vm.provision "shell", path: "../provision/export_go_server.sh 127.0.0.1"

 end