VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu-14.04"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network "private_network", ip: "192.168.33.31"
  config.vm.network "forwarded_port", guest: 8080, host: 8888

  config.vm.define "go" do |g|
    g.vm.box = "go"
  end

  config.vm.provider "virtualbox" do |box|
	box.name = "go"
    box.memory = 524
  end
end